name: CI/CD - Docker Build & Push

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: zacknecesito/k8s-demo-backend
  FRONTEND_IMAGE: zacknecesito/k8s-demo-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ✅ Add test/lint block here
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend test dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run backend linter (flake8)
        run: |
          flake8 backend

      - name: Run backend tests (pytest)
        run: |
          pytest backend/tests

      # 🔽 Docker login and build after tests pass
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
